version: '2'

services:

    web:
        build:
            context: ./
            dockerfile: deploy/web.dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
        
    app:
        build:
            context: ./
            dockerfile: deploy/app.dockerfile
        volumes:
            - ./:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            
    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=stakemoney_db"
            - "MYSQL_USER=stakemoney"
            - "MYSQL_PASSWORD=secret"
        ports:
            - "33061:3306"