version: '3'
services:
  ### PHP-FPM Container
  php-fpm:
    build: ./deploy/php-fpm
    volumes:
      - ./src:/var/www
    expose:
      - "9000"
    links:
      - mysql
      #- redis
  
  ### NGINX Container
  nginx:
    build: ./deploy/nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./src:/var/www
    ports:
      - "8080:80"
      - "443:443"
    links:
      - php-fpm

  ### MySQL Container
  mysql:
    build: ./deploy/mysql
    volumes:
      - /var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}

  ### Redis Container
  #redis:
    #image: redis
    #expose:
        #- "6379"

  ### Application Code Container
  application:
    build: ./deploy/application


  ### Workspace Utilities Container
  workspace:
    build: ./deploy/workspace
    volumes:
      - ./src:/var/www
    links:
      - mysql
      #- redis
    tty: true

volumes:
  src: